### Register new user
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "name": "Joko",
  "id": "joko",
  "password": "joko"
}

### Login user
POST http://localhost:3000/api/users/_login
Content-Type: application/json

{
  "id": "joko",
  "password": "joko"
}

### Get user profile
GET http://localhost:3000/api/users/_current
Authorization: fcdc4824-2bcf-471d-93a4-641a58e4de10
Accept: application/json

### Logout user
DELETE http://localhost:3000/api/users
Authorization: fcdc4824-2bcf-471d-93a4-641a58e4de10
Accept: application/json

### Update user
PATCH http://localhost:3000/api/users/_current
Content-Type: application/json
Accept: application/json
Authorization: fcdc4824-2bcf-471d-93a4-641a58e4de10

{
  "name": "Joko Morro"
}