@startuml

node "Gateway" as gateway {
    node "HTTP" as gatewayHttp
    node "Messaging" as gatewayMessaging
}

node "Delivery" as delivery {
    node "HTTP" as deliveryHttp
    node "Messaging" as deliveryMessaging
}

node "Core" as core {
    node "Entity" as entity
    node "Use Case" as usecase
    node "Repository" as repository
}

database "Database" as database

repository --> database
repository --> entity
usecase --> repository
usecase --> entity
usecase --> gatewayHttp
usecase --> gatewayMessaging
deliveryHttp --> usecase
deliveryMessaging --> usecase

@enduml